"""empty message

Revision ID: 949e7ab31271
Revises: 015a32d18f3f
Create Date: 2020-11-28 16:53:35.333736

"""

# revision identifiers, used by Alembic.
revision = '949e7ab31271'
down_revision = '015a32d18f3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
